#!/usr/bin/env python3
"""Scenario file -> node parameters, and a quick visibility preview.

  scenario.py params  <scenario.yaml> <out_dir>   write per-node parameter files
  scenario.py env     <scenario.yaml>             shell variables for sim.sh
  scenario.py preview <scenario.yaml>             visibility timeline (kinematic)

The scenario (sim/scenarios/*.yaml) is the single source of truth for where
things are. Every node that needs a position gets it from here: PX4's spawn
pose, the offboard route (relative to the spawn point), the ESKF origin the
detector adds back, the entity's path.

`preview` flies the routes at constant speed (no acceleration, no PX4) and
evaluates the same visibility rules as the C++ detector with the same world
geometry, to design routes before spending simulator time. It is an
approximation for planning only; the evaluation always uses what the detector
actually published.
"""
import math
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]


def load(path):
    with open(path) as f:
        sc = yaml.safe_load(f)
    sc["_path"] = str(Path(path).resolve())
    # Scenarios list several entities under `entities`; Phase 1/2 ones have a
    # single `entity`, which becomes a one-element list named after its model.
    if "entities" not in sc:
        sc["entities"] = [dict(sc["entity"], name=sc["entity"]["model"])]
    for e in sc["entities"]:
        e.setdefault("name", e["model"])
        e.setdefault("mode", "pingpong")
    sc.setdefault("entity", sc["entities"][0])
    return sc


def entity_models(sc):
    return [e["model"] for e in sc["entities"]]


def entity_names(sc):
    return [e["name"] for e in sc["entities"]]


def world_file(sc):
    return str((REPO_ROOT / sc["world_file"]).resolve())


def gz_model_name(sc, agent):
    # PX4's px4-rc.gzsim names instance N's model <model>_<N>.
    return f"{sc['px4']['model']}_{agent['id']}"


# ---------------------------------------------------------------- parameters

def write_yaml(path, node, params):
    # `node` is the node's fully qualified name: in a parameter file, a bare
    # name only matches a node with no namespace, and every node here has one.
    with open(path, "w") as f:
        f.write(f"# Generated by scripts/lib/scenario.py from {Path(SC_PATH).name}; do not edit.\n")
        yaml.safe_dump({node: {"ros__parameters": params}}, f, sort_keys=False)


def params(sc, out_dir):
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    det = sc["detector"]
    fus = sc["fusion"]
    ids = [a["id"] for a in sc["agents"]]
    for a in sc["agents"]:
        n = a["id"]
        x0, y0 = a["spawn"][0], a["spawn"][1]
        # Offboard routes are north/east/altitude relative to the start point.
        route_nea = []
        for x, y in a.get("route", []):
            route_nea += [float(y - y0), float(x - x0), float(a["altitude_m"])]
        offboard = {
            "use_sim_time": True,
            "px4_namespace": f"/px4_{n}",
            "altitude_m": float(a["altitude_m"]),
            "cruise_speed_mps": float(a["speed_mps"]),
            "yaw_mode": "hold",
        }
        if "planner" in sc:
            # Phase 3: fly wherever the overwatch planner says.
            offboard.update({"route_source": "goal", "origin_world_enu": [float(v) for v in a["spawn"][:3]],
                             "max_yaw_rate_dps": 60.0, "acceptance_radius_m": 0.8,
                             "acceptance_speed_mps": 0.6, "vertical_speed_mps": 2.0})
        else:
            offboard["route_nea"] = route_nea
        write_yaml(out / f"offboard_{n}.yaml", f"/agent_{n}/offboard", offboard)
        write_yaml(out / f"eskf_{n}.yaml", f"/agent_{n}/eskf", {
            "use_sim_time": True,
            "px4_namespace": f"/px4_{n}",
        })
        write_yaml(out / f"detector_{n}.yaml", f"/agent_{n}/detector", {
            "use_sim_time": True,
            "agent_id": n,
            "agent_frame": f"agent_{n}",
            "entity_frames": entity_names(sc),
            "entity_ref_height_m": float(sc["entity"]["ref_height_m"]),
            "pose_source": det["pose_source"],
            "origin_world_enu": [float(v) for v in a["spawn"][:3]],
            "rate_hz": float(det["rate_hz"]),
            "seed": 1000 + n,
            "world_file": world_file(sc),
            "model_paths": [str(REPO_ROOT / "sim" / "models")],
            "exclude_models": entity_models(sc),
            **{f"camera.{k}": float(v) for k, v in det["camera"].items()},
            **{f"noise.{k}": float(v) for k, v in det["noise"].items()},
        })
    base = {
        "use_sim_time": True,
        "associator": fus["associator"],
        "process_noise": float(fus["process_noise"]),
        "gate_d2": float(fus["gate_d2"]),
        "confirm_hits": int(fus["confirm_hits"]),
        "coast_after_s": float(fus["coast_after_s"]),
        "delete_after_s": float(fus["delete_after_s"]),
        "max_position_sigma_m": float(fus["max_position_sigma_m"]),
        "publish_rate_hz": float(fus["publish_rate_hz"]),
    }
    # The fused picture, and each agent alone through the identical tracker:
    # the single-agent baselines the evaluation compares against.
    write_yaml(out / "fusion.yaml", "/fusion/track_fusion", {**base, "agents": ids})
    for n in ids:
        write_yaml(out / f"baseline_{n}.yaml", f"/baseline_agent_{n}/track_fusion", {**base, "agents": [n]})
    gt_models = entity_models(sc) + [gz_model_name(sc, a) for a in sc["agents"]]
    gt_names = entity_names(sc) + [f"agent_{a['id']}" for a in sc["agents"]]
    if "device" in sc:
        d = sc["device"]
        gt_models.append(d["model"])
        gt_names.append("device")
        # Phase 2: the device fuses what the agents send (centralised at the
        # device), with the same tracker, and draws the see-through overlay.
        write_yaml(out / "device_fusion.yaml", "/device/track_fusion", {**base, "agents": ids})
        write_yaml(out / "overlay.yaml", "/device/overlay", {
            "use_sim_time": True,
            "image_topic": d["camera"]["image_topic"],
            "info_topic": d["camera"]["info_topic"],
            "tracks_topic": "/device/tracks",
            "device_frame": "device",
            "entity_frames": entity_names(sc),
            "camera_mount_xyz": [float(v) for v in d["camera"]["mount_xyz"]],
            "entity_size_m": [float(v) for v in d["entity_size_m"]],
            "entity_ref_height_m": float(sc["entity"]["ref_height_m"]),
            "world_file": world_file(sc),
            "model_paths": [str(REPO_ROOT / "sim" / "models")],
            "exclude_models": entity_models(sc),
        })
    if "planner" in sc:
        pl = sc["planner"]
        write_yaml(out / "planner.yaml", "/overwatch_planner", {
            "use_sim_time": True,
            "agents": ids,
            "altitudes_m": [float(a["altitude_m"]) for a in sc["agents"]],
            "radius_m": float(pl["radius_m"]),
            "interest_radius_m": float(pl["interest_radius_m"]),
            "cell_m": float(pl["cell_m"]),
            "candidates": int(pl["candidates"]),
            "min_separation_m": float(pl["min_separation_m"]),
            "hysteresis": float(pl["hysteresis"]),
            "rate_hz": float(pl["rate_hz"]),
            "duration_s": float(pl.get("duration_s", 0.0)),
            "bounds_xy": [float(v) for v in sc["bounds_xy"]],
            "world_file": world_file(sc),
            "model_paths": [str(REPO_ROOT / "sim" / "models")],
            "exclude_models": entity_models(sc),
            **{f"camera.{k}": float(v) for k, v in det["camera"].items()},
        })
    if "device" in sc:
        d = sc["device"]
        bounds = [float(v) for v in sc.get("bounds_xy", [-1e9, 1e9, -1e9, 1e9])]
        write_yaml(out / "device_controller.yaml", "/device/device_controller", {
            "use_sim_time": True,
            "mode": "teleop" if d.get("control") == "teleop" else "scripted",
            "world": sc["world"],
            "model": d["model"],
            "bounds_xy": bounds,
            "world_file": world_file(sc),
            "model_paths": [str(REPO_ROOT / "sim" / "models")],
            "exclude_models": entity_models(sc),
        })
        write_yaml(out / "game_view.yaml", "/device/game_view", {
            "use_sim_time": True,
            "agents": ids,
            "bounds_xy": bounds,
            "device_hfov_deg": float(d["camera"].get("hfov_deg", 70.0)),
            "device_camera_height_m": float(d["camera"]["mount_xyz"][2]),
            "world_file": world_file(sc),
            "model_paths": [str(REPO_ROOT / "sim" / "models")],
            "exclude_models": entity_models(sc),
        })
    write_yaml(out / "ground_truth.yaml", "/ground_truth_bridge", {
        "use_sim_time": True, "world": sc["world"], "models": gt_models, "names": gt_names,
        "world_file": world_file(sc), "model_paths": [str(REPO_ROOT / "sim" / "models")],
        "exclude_models": entity_models(sc)})
    print(out)


def env(sc):
    """Shell assignments for sim.sh (eval'd)."""
    print(f"SC_WORLD={sc['world']}")
    print(f"SC_WORLD_FILE={world_file(sc)}")
    print(f"SC_PX4_MODEL={sc['px4']['model']}")
    print(f"SC_AGENT_IDS=({' '.join(str(a['id']) for a in sc['agents'])})")
    for a in sc["agents"]:
        x, y, z, yaw = a["spawn"]
        print(f"SC_SPAWN_{a['id']}={x},{y},{z},0,0,{math.radians(yaw):.6f}")
    print(f"SC_POSE_SOURCE={sc['detector']['pose_source']}")
    print(f"SC_PLANNER={1 if 'planner' in sc else 0}")
    d = sc.get("device")
    print(f"SC_DEVICE={1 if d else 0}")
    if d:
        print(f"SC_DEVICE_IMAGE={d['camera']['image_topic']}")
        print(f"SC_DEVICE_INFO={d['camera']['info_topic']}")


# ------------------------------------------------------------------- preview

def building_boxes(path, exclude):
    """Static top-level box collisions (the preview's occluders)."""
    boxes = []
    root = ET.parse(path).getroot()
    for model in root.iter("model"):
        if model.findtext("static", "false").strip() != "true" or model.get("name") in exclude:
            continue
        pose = [float(v) for v in (model.findtext("pose") or "0 0 0 0 0 0").split()]
        for col in model.iter("collision"):
            box = col.find("geometry/box/size")
            if box is None:
                continue
            sx, sy, sz = (float(v) for v in box.text.split())
            # Axis-aligned, unrotated boxes only (enough for the preview).
            boxes.append((pose[0] - sx / 2, pose[0] + sx / 2, pose[1] - sy / 2, pose[1] + sy / 2,
                          pose[2] - sz / 2, pose[2] + sz / 2))
    return boxes


def seg_hits_aabb(a, b, box):
    t0, t1 = 0.0, 1.0
    for i in range(3):
        lo, hi = box[2 * i], box[2 * i + 1]
        d = b[i] - a[i]
        if abs(d) < 1e-12:
            if a[i] < lo or a[i] > hi:
                return False
            continue
        u0, u1 = (lo - a[i]) / d, (hi - a[i]) / d
        if u0 > u1:
            u0, u1 = u1, u0
        t0, t1 = max(t0, u0), min(t1, u1)
        if t0 > t1:
            return False
    return True


def along(points, speed, t, pingpong=False):
    """Position after t seconds along a polyline at constant speed."""
    segs = list(zip(points, points[1:]))
    lens = [math.dist(p, q) for p, q in segs]
    total = sum(lens)
    if pingpong:
        t = t % (2 * total / speed)
        s = t * speed
        if s > total:
            s = 2 * total - s
    else:
        s = min(t * speed, total)
    for (p, q), L in zip(segs, lens):
        if s <= L or L == 0:
            f = s / L if L else 0.0
            return (p[0] + f * (q[0] - p[0]), p[1] + f * (q[1] - p[1]))
        s -= L
    return tuple(points[-1])


def visible(agent_xyz, yaw, target, cam, boxes):
    pitch = math.radians(cam["pitch_down_deg"])
    dx, dy, dz = (target[i] - agent_xyz[i] for i in range(3))
    # Into the body frame (yaw only: level flight), then the pitched camera.
    bx = math.cos(yaw) * dx + math.sin(yaw) * dy
    by = -math.sin(yaw) * dx + math.cos(yaw) * dy
    cx = math.cos(pitch) * bx - math.sin(pitch) * dz
    cz = math.sin(pitch) * bx + math.cos(pitch) * dz
    rng = math.sqrt(dx * dx + dy * dy + dz * dz)
    az = math.atan2(by, cx)
    el = math.atan2(cz, math.hypot(cx, by))
    in_fov = cx > 0 and abs(az) <= math.radians(cam["hfov_deg"]) / 2 and \
        abs(el) <= math.radians(cam["vfov_deg"]) / 2
    in_range = cam["min_range_m"] <= rng <= cam["max_range_m"]
    occluded = any(seg_hits_aabb(agent_xyz, target, b) for b in boxes)
    return in_fov and in_range and not occluded


def preview(sc, dt=0.5, takeoff_s=8.0):
    boxes = building_boxes(world_file(sc), entity_models(sc))
    cam = sc["detector"]["camera"]
    ent = sc["entity"]
    agents = sc["agents"]
    durations = []
    for a in agents:
        pts = [tuple(a["spawn"][:2])] + [tuple(p) for p in a["route"]]
        durations.append(sum(math.dist(p, q) for p, q in zip(pts, pts[1:])) / a["speed_mps"])
    t_end = takeoff_s + max(durations)
    counts = {0: 0, 1: 0, 2: 0}
    per_agent = [0] * len(agents)
    line = []
    t = takeoff_s
    while t <= t_end:
        ex, ey = along([tuple(p) for p in ent["path"]], ent["speed_mps"], t, pingpong=True)
        target = (ex, ey, ent["ref_height_m"])
        n = 0
        for k, a in enumerate(agents):
            pts = [tuple(a["spawn"][:2])] + [tuple(p) for p in a["route"]]
            x, y = along(pts, a["speed_mps"], t - takeoff_s)
            if visible((x, y, a["altitude_m"]), math.radians(a["spawn"][3]), target, cam, boxes):
                n += 1
                per_agent[k] += 1
        counts[min(n, 2)] += 1
        line.append(".12"[min(n, 2)] if n else " ")
        t += dt
    total = sum(counts.values())
    print(f"mission ~{t_end - takeoff_s:.0f} s after takeoff (constant-speed approximation)")
    print(f"entity visible to 0 / 1 / 2 agents: " +
          " / ".join(f"{100 * counts[k] / total:.0f} %" for k in (0, 1, 2)))
    for k, a in enumerate(agents):
        print(f"  agent {a['id']} sees it {100 * per_agent[k] / total:.0f} % of the time")
    print("timeline (" + f"{dt} s per char, blank = nobody, 1 = one agent, 2 = both):")
    s = "".join(line)
    for i in range(0, len(s), 80):
        print(f"  {takeoff_s + i * dt:6.1f} s |{s[i:i + 80]}|")


if __name__ == "__main__":
    if len(sys.argv) < 3 or sys.argv[1] not in ("params", "env", "preview"):
        print(__doc__)
        sys.exit(2)
    SC_PATH = sys.argv[2]
    scenario = load(SC_PATH)
    if sys.argv[1] == "params":
        params(scenario, sys.argv[3])
    elif sys.argv[1] == "env":
        env(scenario)
    else:
        preview(scenario)
